class Data:
    surnames = [
        "Nagy",
        "Kovács",
        "Tóth",
        "Szabó",
        "Horváth",
        "Varga",
        "Kiss",
        "Molnár",
        "Németh",
        "Balogh",
        "Farkas",
        "Lakatos",
        "Papp",
        "Takács",
        "Oláh",
        "Mészáros",
        "Simon",
        "Rácz",
        "Fekete",
        "Szilágyi",
        "Török",
        "Fehér",
        "Balázs",
        "Gál",
    ]
    male_forenames = [
        "Ábel",
        "Ádám",
        "Adrián",
        "Ákos",
        "Alex",
        "András",
        "Attila",
        "Bence",
        "Benedek",
        "Dominik",
        "Gergő",
        "János",
        "József",
        "Krisztián",
        "Máté",
        "Szabolcs",
        "Zsolt",
        "Péter",
        "Tamás",
        "Róbert",
        "Zsombor",
        "Olivér",
    ]
    female_forenames = [
        "Adél",
        "Alexandra",
        "Bianka",
        "Dóra",
        "Eszter",
        "Júlia",
        "Luca",
        "Kata",
        "Noémi",
        "Petra",
        "Szofi",
        "Vanda",
        "Zita",
        "Zsófia",
        "Judit",
        "Odett",
        "Nóra",
        "Natália",
        "Erika",
        "Ildikó",
        "Krisztina",
        "Vivien",
    ]
    settlements = [
        "Szeged",
        "Hódmezővásárhely",
        "Makó",
        "Algyő",
        "Kiskunfélegyháza",
        "Orosháza",
        "Maroslele",
        "Mórahalom",
        "Kiskunhalas",
        "Szentes",
        "Mindszent",
        "Békéscsaba",
        "Kecskemét",
        "Szatymaz",
        "Csongrád",
        "Csanytelek",
        "Felgyő",
        "Tömörkény",
        "Mártély",
        "Székkutas",
        "Kübekháza",
        "Röszke",
        "Tiszasziget",
        "Újszentiván",
        "Sándorfalva",
        "Dóc",
        "Ferencszállás",
        "Klárafalva",
        "Domaszék",
        "Deszk",
        "Csanádpalota",
        "Kiszombor",
        "Ambrózfalva",
        "Apátfalva",
        "Csanádalberti",
        "Földeák",
        "Királyhegyes",
        "Kövegy",
        "Magyarcsanád",
        "Negyér",
        "Nagylak",
        "Óföldeák",
        "Pitvaros",
        "Baks",
        "Balástya",
        "Csengele",
        "Ópusztaszer",
        "Pusztaszer",
        "Öttömös",
        "Forráskút",
        "Üllés",
        "Zákányszék",
    ]
    professions = [
        "Webfejlesztő",
        "DBA",
        "Sportedző",
        "Irodai alkalmazott",
        "Árufeltöltő",
        "Pszichológus",
        "Rendszergazda",
        "Tanár",
        "Takarító",
        "Futár",
        "Színész",
        "Szabó",
        "Építészmérnök",
        "Állatorvos",
        "Történész",
        "Festő",
        "Masszőr",
        "Katona",
        "Rendőr",
        "Könyvelő",
        "Orvos",
        "Ügyvéd",
        "Építész",
        "Mérnök",
        "Programozó",
        "Eladó",
        "Zenész",
        "Énekes",
        "Kertész",
        "Cukrász",
        "Séf",
        "Marketinges",
        "Gyógyszerész",
        "Grafikus",
        "Fotós",
        "Író",
        "Fordító",
        "Ügyintéző",
        "Kémikus",
        "Gyógypedagógus",
        "Jogász",
        "Ápoló",
        "Pilóta",
        "Raktáros",
        "Építőmunkás",
        "Közgazdász",
        "Tűzoltó",
        "Fodrász",
        "Rendezvényszervező",
        "Bíró",
        "Szociális munkás",
        "Villanyszerelő",
        "Földműves",
        "Újságíró",
    ]
    subjects: list[dict[str, str | list[str]]] = [
        {
            "name": "Szakmai angol",
            "topics": [
                "Present simple",
                "Computing, input and output devices",
            ],
        },
        {
            "name": "Munkavállalói ismeretek",
            "topics": [
                "A munka törvénykönyve",
            ],
        },
        {
            "name": "Informatikai és távközlési alapok I. / Elektronika",
            "topics": [
                "Félvezetők",
                "Alapfogalmak",
            ],
        },
        {
            "name": "Informatikai és távközlési alapok I. / ITA1 elmélet és ITA1 gyakorlat",
            "topics": [
                "Neumann-elvek",
            ],
        },
        {
            "name": "Informatikai és távközlési alapok II. / Hálózatok elmélet és gyakorlat",
            "topics": [
                "Cisco alapok",
                "IP címzés",
            ],
        },
        {
            "name": "Informatikai és távközlési alapok II. / ITA2 elmélet és ITA2 gyakorlat",
            "topics": [
                "A számítógép szétszedése és összeszerelése",
            ],
        },
        {
            "name": "Programozási alapok / Web gyakorlat",
            "topics": [
                "HTML, CSS",
            ],
        },
        {
            "name": "Programozási alapok / Python gyakorlat",
            "topics": [
                "Python adatszerkezetek",
                "Python alapok- Űrlap",
            ],
        },
        {
            "name": "IKT projektmunka I. / Python IKT gyakorlat",
            "topics": [
                "Algoritmusok",
            ],
        },
        {
            "name": "IKT projektmunka I. / Web IKT gyakorlat",
            "topics": [
                "Bootstrap",
            ],
        },
        {
            "name": "Asztali alkalmazások fejlesztése / C# alapok és haladó",
            "topics": [
                "OOP",
                "Windows Forms",
            ],
        },
        {
            "name": "Webprogramozás / HTML5, CSS3 kiegészítés",
            "topics": [
                "CSS animations",
                "Accessibility",
            ],
        },
        {
            "name": "Webprogramozás / JavaScript",
            "topics": [
                "Alapok",
                "DOM manipuláció",
            ],
        },
        {
            "name": "Webprogramozás / CMS",
            "topics": [
                "Wordpress",
            ],
        },
        {
            "name": "Adatbázis-kezelés I.",
            "topics": [
                "SQL alapok",
                "Összetett lekérdezések",
            ],
        },
        {
            "name": "Szoftvertesztelés",
            "topics": [
                "White/gray/black box testing",
                "Unit testing",
            ],
        },
    ]
